name: "Testing pipeline"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    name: "${{ matrix.python-version }}: ${{ matrix.python-tools.name }}"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version:
          - "3.12"
        python-tools:
          - name: "Ruff"
            command: "ruff check"
          - name: "MyPy static type checking"
            command: "mypy --strict {src,tests}"
          - name: "Tests"
            command: "pytest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "pip"
          cache-dependency-path: "poetry.lock"
      - name: "Installing Poetry"
        run: pip install --upgrade pip poetry==1.8.3
      - name: "Installing Dependencies"
        run: poetry install
      - name: "${{ matrix.python-tools.name }}"
        run: poetry run ${{ matrix.python-tools.command }}
        env:
          PYTHONPATH: .

